# $Id: Makefile 888 2010-02-12 13:03:30Z vingarzan $
#
# Makefile for the CDiameterPeer AVP Operations module
#
# \author Dragos Vingarzan dragos dot vingarzan -at- fokus dot fraunhofer dot de
#

include ../../Makefile.defs


NAME=cdp_avp.so

DEFS+=-DSER_MOD_INTERFACE
DEFS += -DCDP_FOR_SER
DEFS += -I/usr/include/libxml2 

#libs+=
#includes+=


include ../../Makefile.modules

